/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 529ecf7db300c779027b3e87216ef205)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		DB: D1Database;
		ASSETS: Fetcher;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL">> {}
}
